---

x-common-connect-environment: &common-connect-environment
  CONNECT_BOOTSTRAP_SERVERS: kafka0:29092
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
  CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
  CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: https://schemaregistry0:8285
  CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: https://schemaregistry0:8285
  CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/usr/share/filestream-connectors"
  CONNECT_SECURITY_PROTOCOL: "SSL"
  CONNECT_SSL_KEYSTORE_LOCATION: "/kafka.keystore.jks"
  CONNECT_SSL_KEY_PASSWORD: "secret"
  CONNECT_SSL_KEYSTORE_PASSWORD: "secret"
  CONNECT_SSL_TRUSTSTORE_LOCATION: "/kafka.truststore.jks"
  CONNECT_SSL_TRUSTSTORE_PASSWORD: "secret"
  CONNECT_SSL_CLIENT_AUTH: "requested"
  CONNECT_REST_ADVERTISED_LISTENER: "https"

services:
  kafka0:
    image: confluentinc/cp-kafka:7.9.4
    hostname: kafka0
    container_name: kafka0
    healthcheck:
      test: unset JMX_PORT && KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9999" && kafka-broker-api-versions --bootstrap-server=localhost:9092
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - "9092:9092"
      - "9997:9997"
      - "9093:9093"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,SSL:SSL,EXTERNAL_SSL:SSL,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_HOST_THIRD_MACHINE:PLAINTEXT,INTERNAL_PLAINTEXT:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'SSL://kafka0:29092,EXTERNAL_SSL://localhost:19092,PLAINTEXT_HOST://localhost:9092,PLAINTEXT_HOST_THIRD_MACHINE://kafka:9093,INTERNAL_PLAINTEXT://kafka0:39092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka0:29093'
      KAFKA_LISTENERS: 'SSL://kafka0:29092,CONTROLLER://kafka0:29093,EXTERNAL_SSL://kafka0:19092,PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT_HOST_THIRD_MACHINE://0.0.0.0:9093,INTERNAL_PLAINTEXT://kafka0:39092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'SSL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_SECURITY_PROTOCOL: SSL
      KAFKA_SSL_ENABLED_MECHANISMS: PLAIN,SSL
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: creds
      KAFKA_SSL_KEY_CREDENTIALS: creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: creds
      #KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_SSL_CLIENT_AUTH: 'requested'
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: '' # COMMON NAME VERIFICATION IS DISABLED SERVER-SIDE
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

    volumes:
      - ./ssl/creds:/etc/kafka/secrets/creds
      - ./ssl/kafka.truststore.jks:/etc/kafka/secrets/kafka.truststore.jks
      - ./ssl/kafka.keystore.jks:/etc/kafka/secrets/kafka.keystore.jks

  schemaregistry0:
    image: confluentinc/cp-schema-registry:7.9.4
    depends_on:
      kafka0:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "timeout", "1", "curl", "--silent", "--fail", "http://schemaregistry0:8281/subjects" ]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: SSL://kafka0:29092
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SSL
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /kafka.truststore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: secret
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: /kafka.keystore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: secret
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: secret
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry0
      SCHEMA_REGISTRY_LISTENERS: https://schemaregistry0:8285,http://schemaregistry0:8281
      SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: https
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "https"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: NONE
      SCHEMA_REGISTRY_SSL_CLIENT_AUTHENTICATION: "REQUIRED"
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: /kafka.truststore.jks
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: secret
      SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: /kafka.keystore.jks
      SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: secret
      SCHEMA_REGISTRY_SSL_KEY_PASSWORD: secret
    ports:
      - "8285:8285"
      - "8281:8281"

    volumes:
      - ./ssl/kafka.truststore.jks:/kafka.truststore.jks
      - ./ssl/kafka.keystore.jks:/kafka.keystore.jks

  kafka-connect0:
    build:
      context: ./kafka-connect
      args:
        image: confluentinc/cp-kafka-connect:7.9.4
    ports:
      - "8083:8083"
      - "8082:8082"
    depends_on:
      kafka0:
        condition: service_healthy
      schemaregistry0:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-zv", "kafka-connect0", "8083" ]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      <<: *common-connect-environment
      CONNECT_GROUP_ID: compose-connect0-group
      CONNECT_LISTENERS: "https://kafka-connect0:8083,http://kafka-connect0:8082"
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect0
      CONNECT_OFFSET_STORAGE_TOPIC: _connect0_offset
      CONNECT_STATUS_STORAGE_TOPIC: _connect0_status
      CONNECT_CONFIG_STORAGE_TOPIC: _connect0_configs
    #  CONNECT_LOG4J_ROOT_LOGLEVEL: "DEBUG"
    #  CONNECT_LOG4J_TOOLS_LOGLEVEL: "DEBUG"
    volumes:
      - ./ssl/kafka.truststore.jks:/kafka.truststore.jks
      - ./ssl/kafka.keystore.jks:/kafka.keystore.jks

  # Add a second "connect" node to connect 0
  kafka-connect0-two:
    build:
      context: ./kafka-connect
      args:
        image: confluentinc/cp-kafka-connect:7.9.4
    ports:
      - "8183:8183"
      - "8182:8182"
    depends_on:
      kafka0:
        condition: service_healthy
      schemaregistry0:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-zv", "kafka-connect0-two", "8183" ]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      <<: *common-connect-environment
      CONNECT_GROUP_ID: compose-connect0-group
      CONNECT_LISTENERS: "https://kafka-connect0-two:8183,http://kafka-connect0-two:8182"
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect0-two
      CONNECT_OFFSET_STORAGE_TOPIC: _connect0_offset
      CONNECT_STATUS_STORAGE_TOPIC: _connect0_status
      CONNECT_CONFIG_STORAGE_TOPIC: _connect0_configs
    #  CONNECT_LOG4J_ROOT_LOGLEVEL: "DEBUG"
    #  CONNECT_LOG4J_TOOLS_LOGLEVEL: "DEBUG"
    volumes:
      - ./ssl/kafka.truststore.jks:/kafka.truststore.jks
      - ./ssl/kafka.keystore.jks:/kafka.keystore.jks

  kafka-connect1:
    build:
      context: ./kafka-connect
      args:
        image: confluentinc/cp-kafka-connect:7.9.4
    ports:
      - "8085:8085"
      - "8084:8084"
    depends_on:
      kafka0:
        condition: service_healthy
      schemaregistry0:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-zv", "kafka-connect1", "8085" ]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      <<: *common-connect-environment
      CONNECT_GROUP_ID: compose-connect1-group
      CONNECT_LISTENERS: "https://kafka-connect1:8085,http://kafka-connect1:8084"
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect1
      CONNECT_OFFSET_STORAGE_TOPIC: _connect1_offset
      CONNECT_STATUS_STORAGE_TOPIC: _connect1_status
      CONNECT_CONFIG_STORAGE_TOPIC: _connect1_configs
    #  CONNECT_LOG4J_ROOT_LOGLEVEL: "DEBUG"
    #  CONNECT_LOG4J_TOOLS_LOGLEVEL: "DEBUG"
    volumes:
      - ./ssl/kafka.truststore.jks:/kafka.truststore.jks
      - ./ssl/kafka.keystore.jks:/kafka.keystore.jks
#
#  kafka-init-topics:
#    image: confluentinc/cp-kafka:7.9.4
#    volumes:
#      - ./data/messages.json.txt:/data/messages.json.txt
#    depends_on:
#      kafka0:
#        condition: service_healthy
#    command: "bash -c 'echo Waiting for Kafka to be ready... && \
#               cub kafka-ready -b kafka0:39092 1 30 && \
#               kafka-topics --create --topic users --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka0:39092 && \
#               kafka-topics --create --topic messages --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka0:39092 && \
#               kafka-topics --create --topic customers --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka0:39092 && \
#               kafka-topics --create --topic stores --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka0:39092 && \
#               kafka-topics --create --topic product --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka0:39092 && \
#               kafka-console-producer --bootstrap-server kafka0:39092 --topic users < /data/messages.json.txt'"
#
#  create-connectors-connect0:
#    image: curlimages/curl
#    depends_on:
#      kafka-connect0:
#        condition: service_healthy
#    volumes:
#      - ./connector_connect0:/connectors
#    command: sh -c '/connectors/start.sh'
#
#  create-connectors-connect1:
#    image: curlimages/curl
#    depends_on:
#      kafka-connect1:
#        condition: service_healthy
#    volumes:
#      - ./connector_connect1:/connectors
#    command: sh -c '/connectors/start.sh'

  ksqldb0:
    image: confluentinc/cp-ksqldb-server:7.9.4
    depends_on:
      kafka0:
        condition: service_healthy
      schemaregistry0:
        condition: service_healthy
      kafka-connect0:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-zv", "ksqldb0", "8088" ]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - "8088:8088"
      - "8089:8089"
    environment:
      KSQL_CUB_KAFKA_TIMEOUT: 120
      KSQL_LISTENERS: "https://0.0.0.0:8088,http://0.0.0.0:8089"
      KSQL_BOOTSTRAP_SERVERS: SSL://kafka0:29092
      KSQL_SECURITY_PROTOCOL: SSL
      KSQL_SSL_TRUSTSTORE_LOCATION: /kafka.truststore.jks
      KSQL_SSL_TRUSTSTORE_PASSWORD: secret
      KSQL_SSL_KEYSTORE_LOCATION: /kafka.keystore.jks
      KSQL_SSL_KEYSTORE_PASSWORD: secret
      KSQL_SSL_KEY_PASSWORD: secret
      KSQL_SSL_CLIENT_AUTHENTICATION: REQUIRED
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_CONNECT_URL: https://kafka-connect0:8083
      KSQL_KSQL_SCHEMA_REGISTRY_URL: https://schemaregistry0:8285
      KSQL_KSQL_SERVICE_ID: my_ksql_1
      KSQL_KSQL_HIDDEN_TOPICS: '^_.*'
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
    volumes:
      - ./ssl/kafka.truststore.jks:/kafka.truststore.jks
      - ./ssl/kafka.keystore.jks:/kafka.keystore.jks
